### ISSUE TITLE
Do you need more data?❤

### ISSUE THREAD

**Issue by jexz11** [KeepNoob/PokemonGAN#1]
Hello, I would like to use Stylegan3 for the new Pokemon generation, but unfortunately the computer memory is not enough, but I have downloaded the existing 905 Pokemon 1152 form images (256*256,1280*1280). I can send you the data set if you need.
My email is zhaoyilin97@163.com
<img width="594" alt="1647928801(1)" src="https://user-images.githubusercontent.com/76417800/159417525-087f43e1-1e49-4095-a46d-7cf0391c3731.png">
Of course, if you want, we can exchange data sets, your image style seems to be different from mine, your image is 3D. Mine is the most basic 2D❤❤❤❤❤

**Comment by KeepNoob** [comment]
Thank you for your attention. I think the dataset included most pokemon images that enough for the GAN to train a network. Anyway thanks.
